content_path: content
content_static_path: content/img
template_path: template
template_static_path: assets
default_template: template-doc.html
default_pdf_template: template-pdf.html
filter_paths:
    - tool

callout_types:
    # English
    - "tip"
    - "note"
    - "caution"
    - "warning"
    # Japanese
    - "ヒント" # equiv. of "Tip"
    - "注記" # equiv of "Note"
    - "注意" # equiv. of "Caution"
    - "警告" # equiv. of "Warning"
    # TODO: Add Español (Latin America)

default_filters:
    - multicode_tabs
    - unicode_header_ids
    - buttonize_bootstrap
    - callouts
    - badges
    - link_replacement
    - external_links

languages:
    -   code: en
        display_name: English
        prefix: "/"
    -   code: ja
        display_name: 日本語
        prefix: "/ja/"
#    -   code: es-419
#        display_name: Español (Latinoamerica)
#        prefix: "/es-419/"

targets:
    -   name: en
        lang: en
        prefix: "/"
        display_name: Dactyl Starter Kit #Your name here
        filters:
            - demote_headers
        demote_headers_pdf_only: true
        repository: https://github.com/mduo13/dactyl-starter-kit #Official repo URL here
        logo: /assets/img/dactyl-starter-kit-logo.svg
        url: https://mduo13.github.io/dactyl-starter-kit/ # MUST have a trailing slash
        locale_file: locale/en/LC_MESSAGES/messages.mo
        # google_analytics_tag: "UA-00000000-0"
        ## Enable (and provide your own values) to use Algolia DocSearch:
        # algolia_api_key: 00000000000000000000000000000000
        # algolia_index_name: sitename

    -   name: ja
        lang: ja
        prefix: "/ja/"
        display_name: Dactyl スターター・キット
        filters:
            - demote_headers
        demote_headers_pdf_only: true
        repository: https://github.com/mduo13/dactyl-starter-kit #Official repo URL here
        logo: assets/img/dactyl-starter-kit-logo.svg
        url: https://mduo13.github.io/dactyl-starter-kit/ # MUST have a trailing slash
        locale_file: locale/ja/LC_MESSAGES/messages.mo
        # google_analytics_tag: "UA-00000000-0"
        # algolia_api_key: 00000000000000000000000000000000
        # algolia_index_name: sitename

cover_page:
    name: Home
    html: index.html
    template: template-landing-children.html
    pdf_template: template-pdf-cover.html
    sidebar: disabled

pages:
    -   md: concepts/index.md

    -   md: concepts/index.md
        name: コンセプト
        targets:
            - ja

    -   md: concepts/concept1.md

    -   md: concepts/concept1.ja.md

    -   md: tutorials/index.md

    -   md: tutorials/index.md
        name: チュートリアル
        targets:
            - ja

    -   md: tutorials/tutorial1.md

    -   md: tutorials/tutorial2.md

    -   md: tutorials/tutorial2.md
        parent: tutorials/2/
        html: tutorials/2/nested/
        name: Nested Tutorial
        targets:
            - en
            - ja

    -   md: tutorials/tutorial2.md
        parent: tutorials/2/nested/
        html: tutorials/2/nested/deep/
        name: Deeply Nested Tutorial
        targets:
            - en
            - ja

    -   md: references/index.md

    -   md: references/index.md
        name: リファレンス
        targets:
            - ja

    -   md: references/reference1.md
        targets:
            - en
            - ja

    -   name: REST API Tool Example
        html: rest-api-tool.html
        parent: index.html
        template: template-rest-api-tool.html
        # The following keys configure the REST tool
        methods_js: js/apitool-methods-example.js
        rest_host: https://reqres.in
        doc_base: references-reference1.html
        targets:
            - en
            - ja

# Custom 404 page
    -   name: 404 Not Found
        html: 404.html
        template: template-404.html
        nav_omit: true
        targets:
            - en

# Special sitemap file (for better Google indexing)
    -   name: Sitemap
        html: sitemap.txt
        template: template-sitemap.txt
        nav_omit: true
        targets:
            - en
